In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("data/sales_data.csv")

In [4]:
df

,Order_ID,Date,Customer_ID,Product,Category,Quantity,Price
0,1001,2026-09-01,C001,Laptop Stand,Accessories,2,799
1,1002,2026-09-02,C002,Wireless Mouse,Accessories,3,599
2,1003,2026-09-02,C003,Keyboard,Accessories,1,1299
3,1004,2026-09-03,C004,USB-C Hub,Accessories,2,1499
4,1005,2026-09-04,C005,Webcam,Electronics,1,2199
5,1006,2026-09-05,C006,Headphone,Electronics,2,2499
6,1007,2026-09-06,C007,Power Bank,Electronics,3,1799
7,1008,2026-09-07,C008,Laptop Stand,Accessories,1,799
8,1009,2026-09-08,C009,Keyboard,Accessories,2,1299
9,1010,2026-09-09,C010,Wireless Mouse,Accessories,4,599
10,1011,2026-09-10,C011,Webcam,Electronics,1,2199
11,1012,2026-09-11,C012,Headphone,Electronics,2,2499
12,1013,2026-09-12,C013,USB-C Hub,Accessories,1,1499
13,1014,2026-09-13,C014,Power Bank,Electronics,2,1799
14,1015,2026-09-14,C015,Wireless Mouse,Accessories,3,599

In [5]:
df.head()

,Order_ID,Date,Customer_ID,Product,Category,Quantity,Price
0,1001,2026-09-01,C001,Laptop Stand,Accessories,2,799
1,1002,2026-09-02,C002,Wireless Mouse,Accessories,3,599
2,1003,2026-09-02,C003,Keyboard,Accessories,1,1299
3,1004,2026-09-03,C004,USB-C Hub,Accessories,2,1499
4,1005,2026-09-04,C005,Webcam,Electronics,1,2199

In [7]:
df.shape

(15, 7)

In [8]:
df.columns

Index(['Order_ID', 'Date', 'Customer_ID', 'Product', 'Category', 'Quantity',
       'Price'],
      dtype='str')

In [10]:
df.dtypes

Order_ID       int64
Date             str
Customer_ID      str
Product          str
Category         str
Quantity       int64
Price          int64
dtype: object

In [11]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     15 non-null     int64
 1   Date         15 non-null     str
 2   Customer_ID  15 non-null     str
 3   Product      15 non-null     str
 4   Category     15 non-null     str
 5   Quantity     15 non-null     int64
 6   Price        15 non-null     int64
dtypes: int64(3), str(4)
memory usage: 972.0 bytes

          Order_ID  Quantity        Price
count    15.000000  15.00000    15.000000
mean   1008.000000   2.00000  1465.666667
std       4.472136   0.92582   688.338234
min    1001.000000   1.00000   599.000000
25%    1004.500000   1.00000   799.000000
50%    1008.000000   2.00000  1499.000000
75%    1011.500000   2.50000  1999.000000
max    1015.000000   4.00000  2499.000000

In [12]:
df.isnull().sum()

Order_ID       0
Date           0
Customer_ID    0
Product        0
Category       0
Quantity       0
Price          0
dtype: int64

In [19]:
print("Duplicatates:",
      df.duplicated().sum())
df['Revenue'] = df['Quantity'] * df['Price']
print(df.head())

Duplicatates: 0
   Order_ID        Date Customer_ID         Product     Category  Quantity  \
0      1001  2026-09-01        C001    Laptop Stand  Accessories         2
1      1002  2026-09-02        C002  Wireless Mouse  Accessories         3
2      1003  2026-09-02        C003        Keyboard  Accessories         1
3      1004  2026-09-03        C004       USB-C Hub  Accessories         2
4      1005  2026-09-04        C005          Webcam  Electronics         1

   Price  Revenue
0    799     1598
1    599     1797
2   1299     1299
3   1499     2998
4   2199     2199

In [20]:
print("Total Revenue:",df['Revenue'].sum())
print("Total Quantity Sold:",df['Quantity'].sum())

Total Revenue: 40170
Total Quantity Sold: 30

In [27]:
product_sales = df.groupby('Product')['Quantity'].sum()
print(product_sales)

Product
Headphone          4
Keyboard           3
Laptop Stand       3
Power Bank         5
USB-C Hub          3
Webcam             2
Wireless Mouse    10
Name: Quantity, dtype: int64

In [23]:
# product wise revenue

In [24]:
product_revenue = df.groupby('Product')['Revenue'].sum()
print(product_revenue)

Product
Headphone         9996
Keyboard          3897
Laptop Stand      2397
Power Bank        8995
USB-C Hub         4497
Webcam            4398
Wireless Mouse    5990
Name: Revenue, dtype: int64

In [28]:
print("Most Sold Product:",product_sales.idxmax())
print("Highest Revenue Product:",product_revenue.idxmax())

Most Sold Product: Wireless Mouse
Highest Revenue Product: Headphone

In [29]:
 category_revenue = df.groupby("Category")['Revenue'].sum()

In [30]:
 category_revenue

Category
Accessories    16781
Electronics    23389
Name: Revenue, dtype: int64

In [32]:
print("Highest  Revenue Category:", category_revenue.idxmax())

Highest  Revenue Category: Electronics

In [33]:
daily_revenue = df.groupby("Date")['Revenue'].sum()
print(daily_revenue)

Date
2026-09-01    1598
2026-09-02    3096
2026-09-03    2998
2026-09-04    2199
2026-09-05    4998
2026-09-06    5397
2026-09-07     799
2026-09-08    2598
2026-09-09    2396
2026-09-10    2199
2026-09-11    4998
2026-09-12    1499
2026-09-13    3598
2026-09-14    1797
Name: Revenue, dtype: int64

In [34]:
print("Average Order Value:",df['Revenue'].mean())

Average Order Value: 2678.0